### ISSUE TITLE
Page Tree on main page has been filtered out.

### ISSUE THREAD

**Issue by yo-it-engineer** [nogahighland/confluence-better-pagetree#1]
The extension is supposed to just work on pagetree on the sidebar, not on the main page too.

Before extension
<img width="887" alt="Screen Shot 2020-03-06 at 16 33 39" src="https://user-images.githubusercontent.com/10822260/76062396-f3680580-5fc8-11ea-9658-86f3725a7e86.png">

After extension
<img width="900" alt="Screen Shot 2020-03-06 at 16 36 41" src="https://user-images.githubusercontent.com/10822260/76062384-eea35180-5fc8-11ea-8828-cf7d3dc27669.png">

**Comment by nogahighland** [comment]
Thanks for reporting!
https://github.com/nogahighland/confluence-better-pagetree/pull/2 fixes this issue.
